/**
 * runtime/scene/SceneSerializer.js
 *
 * Pure data <-> World conversion. Scene files are plain JSON so they can
 * be authored by the editor, hand-written, or generated by tools, and
 * loaded identically by the standalone runtime.
 *
 * RUNTIME-ONLY FILE.
 */

import { Transform, TRANSFORM } from "../components/Transform.js";
import { Camera, CAMERA } from "../components/Camera.js";
import { SpriteRenderer, SPRITE_RENDERER } from "../components/SpriteRenderer.js";
import { ShapeRenderer, SHAPE_RENDERER } from "../components/ShapeRenderer.js";
import { StrokePath, STROKE_PATH } from "../components/StrokePath.js";
import { TextRenderer, TEXT_RENDERER } from "../components/TextRenderer.js";
import { SpeechBubble, SPEECH_BUBBLE } from "../components/SpeechBubble.js";
import { ChatLog, CHAT_LOG } from "../components/ChatLog.js";
import { TextInput, TEXT_INPUT } from "../components/TextInput.js";
import { Joystick, JOYSTICK } from "../components/Joystick.js";
import { Rigidbody2D, RIGIDBODY_2D } from "../components/Rigidbody2D.js";
import { Collider2D, COLLIDER_2D } from "../components/Collider2D.js";
import { Light, LIGHT } from "../components/Light.js";
import { ShadowCaster, SHADOW_CASTER } from "../components/ShadowCaster.js";
import { CharacterController, CHARACTER_CONTROLLER } from "../components/CharacterController.js";
import { LightingSettings, LIGHTING_SETTINGS } from "../components/LightingSettings.js";
import { SpriteAnimation, SPRITE_ANIMATION } from "../components/SpriteAnimation.js";
import { AudioSource, AUDIO_SOURCE } from "../components/AudioSource.js";
import { AudioListener, AUDIO_LISTENER } from "../components/AudioListener.js";
import { Tileset, TILESET } from "../components/Tileset.js";
import { Tilemap, TILEMAP } from "../components/Tilemap.js";
import { NavWorld2D, NAV_WORLD_2D } from "../components/NavWorld2D.js";
import { NavAgent2D, NAV_AGENT_2D } from "../components/NavAgent2D.js";
import { Script, SCRIPT } from "../components/Script.js";

const COMPONENT_REGISTRY = {
  [TRANSFORM]: Transform,
  [CAMERA]: Camera,
  [SPRITE_RENDERER]: SpriteRenderer,
  [SHAPE_RENDERER]: ShapeRenderer,
  [STROKE_PATH]: StrokePath,
  [TEXT_RENDERER]: TextRenderer,
  [SPEECH_BUBBLE]: SpeechBubble,
  [CHAT_LOG]: ChatLog,
  [TEXT_INPUT]: TextInput,
  [JOYSTICK]: Joystick,
  [RIGIDBODY_2D]: Rigidbody2D,
  [COLLIDER_2D]: Collider2D,
  [LIGHT]: Light,
  [SHADOW_CASTER]: ShadowCaster,
  [CHARACTER_CONTROLLER]: CharacterController,
  [LIGHTING_SETTINGS]: LightingSettings,
  [SPRITE_ANIMATION]: SpriteAnimation,
  [AUDIO_SOURCE]: AudioSource,
  [AUDIO_LISTENER]: AudioListener,
  [TILESET]: Tileset,
  [TILEMAP]: Tilemap,
  [NAV_WORLD_2D]: NavWorld2D,
  [NAV_AGENT_2D]: NavAgent2D,
  [SCRIPT]: Script,
};

/**
 * @param {import('../core/World.js').World} world
 * @returns {object} plain JSON-serializable scene
 */
export function serializeScene(world) {
  return {
    sceneName: world.sceneName,
    // Hierarchy panel folders (see World.hierarchyFolders' doc comment)
    // — plain data, deep-copied the same way entities/components are
    // just below so a later live edit to world.hierarchyFolders can
    // never retroactively mutate an already-saved snapshot (this
    // matters for UndoManager.js, which round-trips through this exact
    // function for every undo step).
    hierarchyFolders: world.hierarchyFolders.map((f) => ({ ...f })),
    entities: world.getAllEntities().map((entity) => ({
      id: entity.id,
      name: entity.name,
      tag: entity.tag,
      active: entity.active,
      folderId: entity.folderId,
      prefabId: entity.prefabId,
      // Deep-copied for the same "no shared references back to the
      // live entity" reason components are just below — prefabOverrides
      // holds arrays that must not be the SAME array instance a later
      // live edit could push onto.
      prefabOverrides: JSON.parse(JSON.stringify(entity.prefabOverrides || {})),
      components: Object.fromEntries(
        Array.from(entity.components.entries()).map(([type, comp]) => [type, { ...comp }])
      ),
    })),
  };
}

/**
 * Loads scene JSON into the given World, replacing its current contents.
 * @param {import('../core/World.js').World} world
 * @param {object} sceneData
 */
export function deserializeScene(world, sceneData) {
  world.clear();
  world.sceneName = sceneData.sceneName || "Untitled Scene";

  // Restore folders BEFORE entities, so entity.folderId references
  // below always point at an already-existing folder rather than one
  // that hasn't been created yet. Ids are preserved verbatim (like
  // entity ids are, just below) — folder ids can be referenced from
  // both entity.folderId and another folder's own parentId, and both
  // only survive a save/load round-trip if restored exactly as saved.
  world.hierarchyFolders = (sceneData.hierarchyFolders || []).map((f) => ({ ...f }));
  // Keep the auto-increment folder-id counter ahead of every restored
  // id, same reasoning as World.createEntity's id-restore path — so a
  // NEW folder created after loading never collides with one loaded
  // from this scene.
  for (const f of world.hierarchyFolders) {
    const n = parseInt(String(f.id).slice(1), 10);
    if (!Number.isNaN(n) && n >= world._nextFolderId) world._nextFolderId = n + 1;
  }

  for (const entityData of sceneData.entities || []) {
    const entity = world.createEntity(entityData.name, entityData.tag, entityData.id);
    entity.active = entityData.active !== false;
    entity.folderId = entityData.folderId || null;
    entity.prefabId = entityData.prefabId || null;
    entity.prefabOverrides = entityData.prefabOverrides ? JSON.parse(JSON.stringify(entityData.prefabOverrides)) : {};

    for (const [type, data] of Object.entries(entityData.components || {})) {
      const ComponentClass = COMPONENT_REGISTRY[type];
      if (!ComponentClass) {
        console.warn("[SceneSerializer] Unknown component type, skipping:", type);
        continue;
      }
      entity.addComponent(type, new ComponentClass(data));
    }
  }

  return world;
}

/**
 * Serializes a single entity to plain JSON-serializable data (deep —
 * nested arrays like trianglePoints / animation clips are cloned, not
 * shared by reference with the live component). Used by the editor's
 * copy/paste; reconstruction goes through the same COMPONENT_REGISTRY
 * deserializeScene uses, so a pasted entity is identical to one loaded
 * from a scene file.
 * @param {import('../core/World.js').Entity} entity
 * @returns {{ name:string, tag:string, active:boolean, components:Record<string,object> }}
 */
export function serializeEntity(entity) {
  return {
    name: entity.name,
    tag: entity.tag,
    active: entity.active,
    folderId: entity.folderId,
    prefabId: entity.prefabId,
    prefabOverrides: JSON.parse(JSON.stringify(entity.prefabOverrides || {})),
    components: Object.fromEntries(
      Array.from(entity.components.entries()).map(([type, comp]) => [
        type,
        JSON.parse(JSON.stringify(comp)),
      ])
    ),
  };
}

/**
 * Creates a new entity in `world` from serializeEntity output (or a
 * single entity entry from a scene file), reconstructing every
 * component via its registered constructor. Optionally overrides the
 * name (paste uses this to suffix " (Copy)"). Returns the new entity.
 * @param {import('../core/World.js').World} world
 * @param {{ name:string, tag:string, active:boolean, components:Record<string,object> }} data
 * @param {string} [nameOverride]
 * @returns {import('../core/World.js').Entity}
 */
export function instantiateEntity(world, data, nameOverride) {
  const entity = world.createEntity(nameOverride || data.name, data.tag);
  entity.active = data.active !== false;
  // Only carry the folder over if it still actually exists in THIS
  // world — e.g. pasting into a different scene than the one that was
  // copied from, whose folder ids may not line up at all. Falls back
  // to the scene root rather than risk a dangling folderId.
  entity.folderId = data.folderId && world.getHierarchyFolder(data.folderId) ? data.folderId : null;
  // Carries prefab linkage over too (e.g. Ctrl+D duplicating an
  // existing prefab instance produces another linked instance, exactly
  // like Unity duplicating a prefab instance in the Hierarchy). NOT
  // validated against PrefabRegistry here the way folderId is against
  // the world's own folder list just above — this function is
  // runtime-only and has no prefab-catalogue import (see this file's
  // own RULES.txt-driven layering), so an unresolvable prefabId is
  // simply left as-is; every prefab-aware read path (Inspector's Prefab
  // section, PrefabPropagation.js) already treats a prefabId that
  // PrefabRegistry.getPrefab() can't resolve as "not linked" — see
  // PrefabRegistry.deletePrefab()'s doc comment.
  entity.prefabId = data.prefabId || null;
  entity.prefabOverrides = data.prefabOverrides ? JSON.parse(JSON.stringify(data.prefabOverrides)) : {};
  for (const [type, compData] of Object.entries(data.components || {})) {
    const ComponentClass = COMPONENT_REGISTRY[type];
    if (!ComponentClass) continue;
    entity.addComponent(type, new ComponentClass(JSON.parse(JSON.stringify(compData))));
  }
  return entity;
}

/**
 * Clones a LIVE entity already in the world — the runtime counterpart to
 * instantiateEntity (which builds from a plain-data payload instead).
 * Used by ScriptAPI.spawn() (this.spawn() / global spawn() in user
 * scripts) to spawn a runtime copy of any existing entity, exactly like
 * Unity's Object.Instantiate(original).
 *
 * Goes through the SAME serializeEntity -> COMPONENT_REGISTRY reconstruct
 * path as editor copy/paste, so a clone is byte-for-byte identical to the
 * source (deep-cloned components, fresh entity id, no shared references)
 * with zero special-casing per component type. Nothing here touches
 * Rapier bodies, sprites, or script instances directly — those are all
 * driven by other systems that re-query world.entities every frame
 * (PhysicsWorld.step, RenderSystem.update, ScriptSystem's incremental
 * _initScripts pass), so a clone "just works" with physics/rendering/
 * scripting the moment it's added to the world, the same way any other
 * runtime-created entity does.
 *
 * @param {import('../core/World.js').World} world
 * @param {import('../core/Entity.js').Entity} source entity to copy
 * @param {{ name?: string, x?: number, y?: number }} [overrides]
 *   name: rename the clone (defaults to the source's own name, matching
 *   Unity — Instantiate() does not auto-suffix "(Clone)").
 *   x/y: place the clone at a specific position instead of the source's
 *   own Transform position (only applied if the entity has a Transform).
 * @returns {import('../core/Entity.js').Entity} the new entity
 */
export function cloneEntity(world, source, overrides) {
  const data = serializeEntity(source);
  const entity = instantiateEntity(world, data, overrides && overrides.name);
  if (overrides && (overrides.x !== undefined || overrides.y !== undefined)) {
    const t = entity.getComponent(TRANSFORM);
    if (t) {
      if (overrides.x !== undefined) t.x = overrides.x;
      if (overrides.y !== undefined) t.y = overrides.y;
    }
  }
  // Flag so ScriptSystem's incremental init (_initNewInstances) knows to
  // fire onClone() and set this.isClone = true for this entity's own
  // script instances. Not part of the Entity class's own fields (see
  // core/Entity.js) since it's a one-off runtime marker relevant only to
  // ScriptSystem, not scene data — deliberately left OUT of
  // serializeEntity/serializeScene so a clone that later gets saved back
  // into a scene (e.g. editor "Apply changes") is indistinguishable from
  // a hand-placed entity, exactly like Unity: Instantiate()'d objects
  // carry no special marker once baked into a scene.
  entity.__isClone = true;
  return entity;
}
